#! /bin/bash
set -ue
# 関数の宣言は必ず事前に1行にしておくこと!

# トップレベル関数の行をリストアップする
lines=$(cat main.go | grep -n -e "func\s" )
# echo "${lines}"

# (ただし、FPROF_IGNOREが入っている行とmain関数は除く。)
lines=$(echo "${lines}" | grep -v "FPROF_IGNORE" | grep -v "\smain()\s")
# echo "${lines}"

# 行番号のみを手に入れ、逆順にする。
lines=$(echo "${lines}" | awk -F ':' '{print $1}' | sort -rn) 
echo "\nInsert codes to lines:"
echo "${lines}\n"

# macの標準のsedは使わずに、GNU sedを使う。
# なければ、brew install gnu-sed でインストールする。
if [ "$(uname)" == 'Darwin' ]; then
cmdSed="gsed"
else
cmdSed="sed"
fi

# ファイルの後ろの行からコード片を追記する。
cp main.go main.fprof.go
for i in ${lines}
do
${cmdSed} -i "${i} s/$/fProfFinalizer := FProf();defer fProfFinalizer.End()/g" main.fprof.go
done

${cmdSed} -i "1i // Code generated by fprof.sh; DO NOT EDIT." main.fprof.go
echo "success!"